# Generated by Django 4.2.4 on 2023-08-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='application_deadline',
        ),
    ]
