# Generated by Django 4.2.4 on 2023-08-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_jobposting_application_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='user',
        ),
    ]
