# Generated by Django 4.2.4 on 2023-08-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_jobposting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='application_checkbox',
            field=models.BooleanField(choices=[('on', 'hiring'), ('off', 'hiring_closed')], default=None),
            preserve_default=False,
        ),
    ]
