# Generated by Django 4.2.4 on 2023-08-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_jobposting_application_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='application_checkbox',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='hiring_status',
            field=models.BooleanField(default=False),
        ),
    ]
