# Generated by Django 4.2.4 on 2023-08-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jobposting_salary_range_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='salary_range_max',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='salary_range_min',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
