# Generated by Django 4.2.4 on 2023-08-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_jobposting_salary_range_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='hiring_status',
            field=models.CharField(choices=[('hiring', 'Hiring'), ('hiring_closed', 'Hiring Closed')], default='hiring_closed', max_length=20),
        ),
    ]
