# Generated by Django 4.2.4 on 2023-08-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_jobposting_hiring_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='hiring_status',
        ),
    ]
