# Generated by Django 4.2.4 on 2023-08-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_jobposting_hiring_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='hiring_status',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('Hiring', 'Hiring'), ('Hiring Closed', 'Hiring Closed')], default='Hiring', max_length=20),
        ),
    ]
