# Generated by Django 4.2.4 on 2023-08-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_jobposting_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
