# Generated by Django 4.2.4 on 2023-09-04 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_remove_jobposting_selected_selectedstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedstudent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
