# Generated by Django 4.2.4 on 2023-09-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_selectedstudent_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedstudent',
            name='message',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
