# Generated by Django 4.2.4 on 2023-08-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_job_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='media/resume/'),
        ),
    ]
