# Generated by Django 4.2.4 on 2023-08-23 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0004_alter_resume_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalSkill',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('hobbies_name', models.CharField(blank=True, max_length=200, null=True)),
                ('language_name', models.CharField(blank=True, max_length=200, null=True)),
                ('skill_name', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='languageskill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentskill',
            name='user',
        ),
        migrations.DeleteModel(
            name='InterestHobbies',
        ),
        migrations.DeleteModel(
            name='LanguageSkill',
        ),
        migrations.DeleteModel(
            name='StudentSkill',
        ),
    ]
