# Generated by Django 4.2.4 on 2023-08-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_additionalskill_remove_languageskill_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='resume/'),
        ),
    ]
