# Generated by Django 4.2.4 on 2023-08-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_alter_job_application_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_application',
            name='interested',
            field=models.BooleanField(default=False),
        ),
    ]
