# Generated by Django 4.2.4 on 2023-08-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_alter_resume_resume_file'),
        ('Student', '0007_alter_job_application_interested'),
    ]

    operations = [
    ]
