# Generated by Django 4.2.4 on 2023-09-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_merge_20230830_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(blank=True, choices=[('internship', 'Internship'), ('full_time', 'Full Time')], default='full_time', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
