# Generated by Django 4.2.4 on 2023-09-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_merge_20230902_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='email',
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(blank=True, choices=[('internship', 'Internship'), ('full_time', 'Full Time')], default='full_time', max_length=20, null=True),
        ),
    ]
