# Generated by Django 4.2.4 on 2023-09-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_alter_experience_job_type_alter_personalinfo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='email',
        ),
    ]
