# Generated by Django 4.2.4 on 2023-09-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_merge_20230830_1911'),
        ('Student', '0009_remove_personalinfo_email_alter_experience_job_type'),
    ]

    operations = [
    ]
