# Generated by Django 4.2.4 on 2023-09-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_alter_experience_job_type_alter_personalinfo_email'),
        ('Student', '0010_merge_20230905_1140'),
    ]

    operations = [
    ]
