# Generated by Django 4.2.4 on 2023-09-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_merge_20230905_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='email',
        ),
    ]
